FRC Paradigm Shift #1259: HomeTarget Class Reference
HomeTarget Class Reference
Public Member Functions
HomeTarget (frc::XboxController *controller, FlywheelSubsystem *flywheel, TurretSubsystem *turret, HoodSubsystem *hood, VisionSubsystem *vision, bool *turretready, bool *firing, bool *finished)
void Initialize () override
void Execute () override
bool IsFinished () override
void End (bool interrupted) override
Private Attributes
frc::XboxController * m_controller
FlywheelSubsystem * m_flywheel
TurretSubsystem * m_turret
HoodSubsystem * m_hood
VisionSubsystem * m_vision
bool * m_turretready
bool * m_firing
bool * m_finished
Detailed Description
Definition at line 17 of file HomeTarget.h.
Constructor & Destructor Documentation
HomeTarget::HomeTarget (frc::XboxController * controller, FlywheelSubsystem * flywheel, TurretSubsystem * turret, HoodSubsystem * hood, VisionSubsystem * vision, bool * turretready, bool * firing, bool * finished) explicit
Definition at line 5 of file HomeTarget.cpp.
References m_finished, m_firing, and m_turretready.
  : m_controller(controller)
  , m_flywheel(flywheel)
  , m_turret(turret)
  , m_hood(hood)
  , m_vision(vision)
  , m_turretready(turretready)
  , m_firing(firing)
  , m_finished(finished)
 {
     AddRequirements({flywheel, turret, hood, vision});
     *m_turretready = false;
     *m_firing = false;
     *m_finished = false;
 }
Member Function Documentation
void HomeTarget::Initialize () override
Definition at line 23 of file HomeTarget.cpp.
References m_finished, m_firing, and m_turretready.
 {
     *m_turretready = false;
     *m_firing = false;
     *m_finished = false;
 }
void HomeTarget::Execute () override
Definition at line 30 of file HomeTarget.cpp.
References VisionSubsystem::GetActive(), VisionSubsystem::GetAngle(), VisionSubsystem::GetDistance(), FlywheelSubsystem::IsAtRPM(), FlywheelSubsystem::IsAtRPMPositive(), TurretSubsystem::isAtSetpoint(), FlywheelConstants::kFiringRPMMultiplier, FlywheelConstants::kHomingRPMMultiplier, TurretConstants::kMaxOverrideAngle, m_controller, m_firing, m_flywheel, m_hood, m_turret, m_turretready, m_vision, HoodSubsystem::Set(), FlywheelSubsystem::SetRPM(), and TurretSubsystem::TurnToRelative().
 {
     // Homes flywheel, turret, and hood to the right angles through a formula
     // SmartDashboard::PutBoolean("TEST_VIS_ACTIVE", m_vision->GetActive());
     if (!m_vision->GetActive())
         return;
     double distance = m_vision->GetDistance();
     //y\ =\ 1687.747+15.8111x-0.0594079x^{2}+0.00008292342x^{3}
     // Increased flywheel at upper ends 3/18/21
     //y\ =\ 1687.747+15.8111x-0.058079x^{2}+0.00008892342x^{3}
     double flywheelspeed = 1687.747 + 15.8111 * distance - 0.058079 * pow(distance, 2) + 0.00008892342 * pow(distance, 3);
     // Quintic regression calculated 3/27
     // https://mycurvefit.com/
     //y=11.20831-0.2645223*x+0.002584349*x^{2}-0.00001250923*x^{3}+2.986403\cdot10^{-8}*x^{4}-2.81104\cdot10^{-11}*x^{5}
     double hoodangle = 11.20831 - 0.2645223 * distance + 0.002584349 * pow(distance, 2) - 0.00001250923 * pow(distance, 3) + 2.986403E-8 * pow(distance, 4) - 2.81104E-11 * pow(distance, 5);
     double angleOverride = 0;
     double turretXRot = m_controller->GetY(frc::GenericHID::kRightHand) * -1.0;
     double turretYRot = m_controller->GetX(frc::GenericHID::kRightHand);
     // if (m_controller->GetBumperPressed(GenericHID::JoystickHand::kRightHand)) {
     //     flywheelspeed = FlywheelConstants::kTrenchRPM;
     //     hoodangle = HoodConstants::kTrenchPosition;
     //     if (Util::Deadzone(sqrt(pow(turretXRot, 2) + pow(turretYRot, 2)), OIConstants::kDeadzoneAbsRot) == 0) {
     //         turretXRot = 0;
     //         turretYRot = 0;
     //     }
     //     double rotPosition = atan2f(turretYRot, turretXRot);
     //     rotPosition *= 360.0/Math::kTau;
     //     m_turret->TurnToRobot(rotPosition);
     // }
     // else {
         angleOverride = turretXRot * TurretConstants::kMaxOverrideAngle;
         m_turret->TurnToRelative(m_vision->GetAngle() + angleOverride);
     // }
     flywheelspeed *= FlywheelConstants::kHomingRPMMultiplier;
     if (*m_firing)
         flywheelspeed *= FlywheelConstants::kFiringRPMMultiplier;
     if (distance > 200) {
         flywheelspeed += 100;
     }
     m_flywheel->SetRPM(flywheelspeed);
     m_hood->Set(hoodangle);
     SmartDashboard::PutBoolean("D_FIRE_AT_RPM", m_flywheel->IsAtRPM());
     SmartDashboard::PutBoolean("D_FIRE_AT_SET", m_turret->isAtSetpoint());
     // if running manual trench fire
     // if (m_controller->GetBumper(GenericHID::JoystickHand::kRightHand))
     // {
     //     // if call to launch
     //     if (m_controller->GetYButtonPressed())
     //     {
     //         *m_turretready = true;
     //     }
     // }
     // // if at position, set turret ready to true
     // else
     if (m_flywheel->IsAtRPMPositive() && m_turret->isAtSetpoint())
     {
         *m_turretready = true;
     }
 }
bool HomeTarget::IsFinished () override
Definition at line 98 of file HomeTarget.cpp.
References m_finished.
 {
     // SmartDashboard::PutBoolean("TEST_FIRE_FINISIHED", *m_finished);
     return *m_finished;
 }
void HomeTarget::End (bool interrupted) override
Definition at line 104 of file HomeTarget.cpp.
References FlywheelConstants::kIdleRPM, HoodConstants::kMax, TurretConstants::kStartingPositionDegrees, m_finished, m_flywheel, m_hood, m_turret, m_turretready, HoodSubsystem::Set(), FlywheelSubsystem::SetRPM(), and TurretSubsystem::TurnTo().
{
     *m_finished = false;
     *m_turretready = false;
     m_flywheel->SetRPM(FlywheelConstants::kIdleRPM);
     m_hood->Set(HoodConstants::kMax);
     m_turret->TurnTo(TurretConstants::kStartingPositionDegrees);
 }
Member Data Documentation
frc::XboxController* HomeTarget::m_controller private
Definition at line 30 of file HomeTarget.h.
FlywheelSubsystem* HomeTarget::m_flywheel private
Definition at line 31 of file HomeTarget.h.
TurretSubsystem* HomeTarget::m_turret private
Definition at line 32 of file HomeTarget.h.
HoodSubsystem* HomeTarget::m_hood private
Definition at line 33 of file HomeTarget.h.
VisionSubsystem* HomeTarget::m_vision private
Definition at line 34 of file HomeTarget.h.
bool* HomeTarget::m_turretready private
Definition at line 35 of file HomeTarget.h.
bool* HomeTarget::m_firing private
Definition at line 36 of file HomeTarget.h.
bool* HomeTarget::m_finished private
Definition at line 37 of file HomeTarget.h.
The documentation for this class was generated from the following files:
src/main/include/commands/HomeTarget.h
src/main/cpp/commands/HomeTarget.cpp