FRC Paradigm Shift #1259: CyclerLaunch Class Reference
CyclerLaunch Class Reference
Public Member Functions
CyclerLaunch (CyclerSubsystem *subsystem, bool *turretready, bool *firing, bool *finished, double launchtime)
void Initialize () override
void Execute () override
bool IsFinished () override
void End (bool interrupted) override
Private Attributes
CyclerSubsystem * m_cycler
Timer m_timer
bool * m_turretready
bool * m_firing
bool * m_finished
double m_launchtime
Detailed Description
Definition at line 13 of file CyclerLaunch.h.
Constructor & Destructor Documentation
CyclerLaunch::CyclerLaunch (CyclerSubsystem * subsystem, bool * turretready, bool * firing, bool * finished, double launchtime) explicit
Definition at line 6 of file CyclerLaunch.cpp.
References m_finished, m_firing, and m_turretready.
  : m_cycler(subsystem)
  , m_turretready(turretready)
  , m_firing(firing)
  , m_finished(finished)
  , m_launchtime(launchtime)
 {
   AddRequirements({subsystem});
   *m_turretready = false;
   *m_firing = false;
   *m_finished = false;
 }
Member Function Documentation
void CyclerLaunch::Initialize () override
Definition at line 21 of file CyclerLaunch.cpp.
References m_finished, m_firing, m_timer, and m_turretready.
 {
     m_timer.Reset();
     m_timer.Stop();
     *m_turretready = false;
     *m_firing = false;
     *m_finished = false;
 }
void CyclerLaunch::Execute () override
Definition at line 30 of file CyclerLaunch.cpp.
References CyclerConstants::kFeederSpeed, CyclerConstants::kTurnTableSpeed, m_cycler, m_firing, m_timer, m_turretready, CyclerSubsystem::SetFeeder(), and CyclerSubsystem::SetTurnTable().
 {
     if (*m_turretready)
     {
         *m_firing = true;
         m_timer.Start();
     }
     if (*m_firing)
     {
         m_cycler->SetTurnTable(kTurnTableSpeed);
         m_cycler->SetFeeder(kFeederSpeed);
     }
     else
     {
         m_cycler->SetTurnTable(0);
         m_cycler->SetFeeder(0);
     }
     // SmartDashboard::PutBoolean("TEST_READY_TO_FIRE", *m_turretready);
     // SmartDashboard::PutBoolean("TEST_FIRING", *m_firing);
 }
bool CyclerLaunch::IsFinished () override
Definition at line 54 of file CyclerLaunch.cpp.
References m_launchtime, and m_timer.
{
     return m_timer.Get() > m_launchtime;
 }
void CyclerLaunch::End (bool interrupted) override
Definition at line 58 of file CyclerLaunch.cpp.
References m_cycler, m_finished, m_firing, m_timer, CyclerSubsystem::ResetSensor(), CyclerSubsystem::SetFeeder(), and CyclerSubsystem::SetTurnTable().
{
     *m_finished = true;
     *m_firing = false;
     m_timer.Stop();
     m_cycler->ResetSensor();
     m_cycler->SetFeeder(0);
     m_cycler->SetTurnTable(0);
     // SmartDashboard::PutBoolean("TEST_FIRING", *m_firing);
 }
Member Data Documentation
CyclerSubsystem* CyclerLaunch::m_cycler private
Definition at line 26 of file CyclerLaunch.h.
Timer CyclerLaunch::m_timer private
Definition at line 27 of file CyclerLaunch.h.
bool* CyclerLaunch::m_turretready private
Definition at line 28 of file CyclerLaunch.h.
bool* CyclerLaunch::m_firing private
Definition at line 29 of file CyclerLaunch.h.
bool* CyclerLaunch::m_finished private
Definition at line 30 of file CyclerLaunch.h.
double CyclerLaunch::m_launchtime private
Definition at line 31 of file CyclerLaunch.h.
The documentation for this class was generated from the following files:
src/main/include/commands/CyclerLaunch.h
src/main/cpp/commands/CyclerLaunch.cpp