FRC Paradigm Shift #1259: TurretSubsystem Class Reference
TurretSubsystem Class Reference
Public Member Functions
TurretSubsystem (Gyro *gyro)
void Periodic () override
Will be called periodically whenever the CommandScheduler runs.
void TurnTo (double angle, double minAngle=TurretConstants::kMinAngle, double maxAngle=TurretConstants::kMaxAngle)
void TurnToRobot (double robotAngle)
void TurnToField (double desiredAngle)
void TurnToRelative (double angle, double minAngle=TurretConstants::kMinAngle, double maxAngle=TurretConstants::kMaxAngle)
bool isAtSetpoint ()
Returns whether or not the turret is at the desired setpoint.
void ResetPosition ()
Resets the turret back to the initial default position.
void SetNewPIDValues ()
Set new PID Values for the turret from on the fly SmartDashboard values.
Protected Member Functions
double TicksToDegrees (double ticks)
double DegreesToTicks (double degrees)
Private Attributes
TalonSRX m_turretmotor
775 that rurns the shooting mechanism
double m_currentAngle
The current angle of the turret, in degrees.
Gyro * m_gyro
Gyro to determine field relative angles, from RobotContainer.
Detailed Description
Definition at line 19 of file TurretSubsystem.h.
Constructor & Destructor Documentation
TurretSubsystem::TurretSubsystem (Gyro * gyro)
Definition at line 9 of file TurretSubsystem.cpp.
References DegreesToTicks(), FlywheelConstants::kD, TurretConstants::kDegreePIDStopRange, FlywheelConstants::kI, TurretConstants::kInverted, FlywheelConstants::kMaxOut, FlywheelConstants::kMinOut, FlywheelConstants::kP, TurretConstants::kSensorPhase, TurretConstants::kStartingPositionDegrees, TurretConstants::kTimeout, m_currentAngle, and m_turretmotor.
     : m_turretmotor(kMotorPort)
     , m_gyro(gyro)
 {
     m_turretmotor.ConfigSelectedFeedbackSensor(FeedbackDevice::QuadEncoder, 0, kTimeout);
     m_turretmotor.SetNeutralMode(NeutralMode::Brake);
     m_turretmotor.SetSensorPhase(kSensorPhase);
     m_turretmotor.SetInverted(kInverted);
     m_turretmotor.Config_kP(0, kP, kTimeout);
     m_turretmotor.Config_kI(0, kI, kTimeout);
     m_turretmotor.Config_kD(0, kD, kTimeout);
     m_turretmotor.ConfigNominalOutputForward(kMinOut, kTimeout);
     m_turretmotor.ConfigNominalOutputReverse(kMinOut * -1.0, kTimeout);
     m_turretmotor.ConfigPeakOutputForward(kMaxOut, kTimeout);
     m_turretmotor.ConfigPeakOutputReverse(kMaxOut * -1.0, kTimeout);
     //m_turretmotor.ConfigClosedloopRamp()
     m_turretmotor.ConfigAllowableClosedloopError(0, DegreesToTicks(kDegreePIDStopRange), kTimeout);
     m_turretmotor.SetSelectedSensorPosition(DegreesToTicks(kStartingPositionDegrees), 0, kTimeout);
     m_turretmotor.Set(ControlMode::Position, DegreesToTicks(kStartingPositionDegrees));
     m_currentAngle = kStartingPositionDegrees;
     // frc::SmartDashboard::PutNumber("T_T_P", kP);
     // frc::SmartDashboard::PutNumber("T_T_I", kI);
     // frc::SmartDashboard::PutNumber("T_T_D", kD);
     // frc::SmartDashboard::PutNumber("T_T_Max", kMaxOut);
 }
Member Function Documentation
void TurretSubsystem::Periodic () override
Will be called periodically whenever the CommandScheduler runs.
Definition at line 40 of file TurretSubsystem.cpp.
References DegreesToTicks(), m_currentAngle, m_turretmotor, and TicksToDegrees().
 {
     SmartDashboard::PutNumber("D_T_CAngle", TicksToDegrees(m_turretmotor.GetSelectedSensorPosition()));
     // SmartDashboard::PutNumber("D_T_DAngle", TicksToDegrees(m_turretmotor.GetClosedLoopTarget()));
     // SmartDashboard::PutNumber("D_T_Error", TicksToDegrees(m_turretmotor.GetClosedLoopError(0)));
     // SmartDashboard::PutNumber("D_T_Output", m_turretmotor.GetMotorOutputPercent());
     m_turretmotor.Set(ControlMode::Position, DegreesToTicks(m_currentAngle));
 }
void TurretSubsystem::TurnTo (double angle, double minAngle = TurretConstants::kMinAngle, double maxAngle = TurretConstants::kMaxAngle)
Turns the turret to a specified angle on the turret Most calculations currently depend on counter clockwise turning, with 0 as "front"
Parameters
angle Angle desired to turn to, must be within the boundaries of the turret, must be positive, in degrees
Definition at line 49 of file TurretSubsystem.cpp.
References m_currentAngle, and Util::ZeroTo360Degs().
 {
     // safeguard
     angle = Util::ZeroTo360Degs(angle);
     // Turret is not set if desired angle is within the deadzone area
     if (angle >= minAngle && angle <= maxAngle)
         m_currentAngle = angle;
     // else if (angle <= minAngle)
     //     m_currentAngle = minAngle;
     // else if (angle >= maxAngle)
     //     m_currentAngle = maxAngle;
 }
void TurretSubsystem::TurnToRobot (double robotAngle)
Turns the turret based on the robot angle
Parameters
robotAngle Robot angle to turn to, must be positive, in degrees
Definition at line 62 of file TurretSubsystem.cpp.
References TurretConstants::kTurretToRobotAngleOffset, TurnTo(), and Util::ZeroTo360Degs().
 {
     double angle = robotAngle - kTurretToRobotAngleOffset;
     TurnTo(Util::ZeroTo360Degs(angle));
 }
void TurretSubsystem::TurnToField (double desiredAngle)
Turns the turret based on an absolute field angle
Parameters
deisredAngle Field angle to turn to, must be positive
Definition at line 68 of file TurretSubsystem.cpp.
References Gyro::GetHeading(), m_gyro, TurnToRobot(), and Util::ZeroTo360Degs().
 {
     // safeguard
     desiredAngle = Util::ZeroTo360Degs(desiredAngle);
     double gyroAngle = Util::ZeroTo360Degs(m_gyro->GetHeading());
     // The difference between the field and robot is the desired angle to set relative to the robot
     double angle = gyroAngle - desiredAngle;
     TurnToRobot(Util::ZeroTo360Degs(angle));
 }
void TurretSubsystem::TurnToRelative (double angle, double minAngle = TurretConstants::kMinAngle, double maxAngle = TurretConstants::kMaxAngle)
Turns the turret to an angle added to the current robot position
Parameters
angle Angle that should be added to the robot position and turned to, can be either positive or negative, in degrees
Definition at line 78 of file TurretSubsystem.cpp.
References m_turretmotor, TicksToDegrees(), TurnTo(), and Util::ZeroTo360Degs().
 {
     double desiredAngle = TicksToDegrees(m_turretmotor.GetSelectedSensorPosition());
     angle = Util::ZeroTo360Degs(angle);
     desiredAngle += angle;
     desiredAngle = Util::ZeroTo360Degs(desiredAngle);
     TurnTo(desiredAngle, minAngle, maxAngle);
 }
bool TurretSubsystem::isAtSetpoint ()
Returns whether or not the turret is at the desired setpoint.
Definition at line 87 of file TurretSubsystem.cpp.
References DegreesToTicks(), TurretConstants::kDegreeStopRange, and m_turretmotor.
 {
     return fabs(m_turretmotor.GetClosedLoopError()) <= DegreesToTicks(kDegreeStopRange);
 }
void TurretSubsystem::ResetPosition ()
Resets the turret back to the initial default position.
Definition at line 92 of file TurretSubsystem.cpp.
References DegreesToTicks(), TurretConstants::kStartingPositionDegrees, TurretConstants::kTimeout, and m_turretmotor.
 {
     m_turretmotor.SetSelectedSensorPosition(DegreesToTicks(kStartingPositionDegrees), 0, kTimeout);
 }
void TurretSubsystem::SetNewPIDValues ()
Set new PID Values for the turret from on the fly SmartDashboard values.
CONFIRMED: OVERUNNING THE ENTIRE LOOP Bug
Definition at line 97 of file TurretSubsystem.cpp.
 {
     // double p = frc::SmartDashboard::GetNumber("T_T_P", kP);
     // double i = frc::SmartDashboard::GetNumber("T_T_I", kI);
     // double d = frc::SmartDashboard::GetNumber("T_T_D", kD);
     // double max = frc::SmartDashboard::GetNumber("T_T_Max", kMaxOut);
     // m_turretmotor.Config_kP(0, p, kTimeout);
     // m_turretmotor.Config_kI(0, i, kTimeout);
     // m_turretmotor.Config_kD(0, d, kTimeout);
     // m_turretmotor.ConfigPeakOutputForward(max, kTimeout);
     // m_turretmotor.ConfigPeakOutputReverse(max * -1.0, kTimeout);
 }
double TurretSubsystem::TicksToDegrees (double ticks) protected
Converts motor ticks into turret rotation, in degrees
Parameters
ticks Number of ticks to be converted
Definition at line 112 of file TurretSubsystem.cpp.
References TurretConstants::kDegreesPerRev, TurretConstants::kMotorRevPerRev, and TurretConstants::kTicksPerRev.
 {
     double rev = ticks / kTicksPerRev;
     double turretrev = rev * kMotorRevPerRev;
     return turretrev * kDegreesPerRev;
 }
double TurretSubsystem::DegreesToTicks (double degrees) protected
Converts turret rotation in degrees into motor ticks
Parameters
degrees Number of degrees to be converted
Definition at line 120 of file TurretSubsystem.cpp.
References TurretConstants::kDegreesPerRev, TurretConstants::kMotorRevPerRev, and TurretConstants::kTicksPerRev.
 {
     double turretrev = degrees / kDegreesPerRev;
     double rev = turretrev / kMotorRevPerRev;
     return rev * kTicksPerRev;
 }
Member Data Documentation
TalonSRX TurretSubsystem::m_turretmotor private
775 that rurns the shooting mechanism
Definition at line 64 of file TurretSubsystem.h.
double TurretSubsystem::m_currentAngle private
The current angle of the turret, in degrees.
Definition at line 66 of file TurretSubsystem.h.
Gyro* TurretSubsystem::m_gyro private
Gyro to determine field relative angles, from RobotContainer.
Definition at line 68 of file TurretSubsystem.h.
The documentation for this class was generated from the following files:
src/main/include/subsystems/TurretSubsystem.h
src/main/cpp/subsystems/TurretSubsystem.cpp