FRC Paradigm Shift #1259: SwerveModule2 Class Reference
SwerveModule2 Class Reference
Public Member Functions
SwerveModule2 (int driveMotorChannel, int turningMotorChannel, GetPulseWidthCallback pulseWidthCallback, CANifier::PWMChannel pwmChannel, bool driveEncoderReversed, double offSet, const std::string &name)
void Periodic ()
frc::SwerveModuleState GetState ()
void SetDesiredState (frc::SwerveModuleState &state)
void ResetEncoders ()
Resets the drive motor encoders to 0.
void ResetRelativeToAbsolute ()
Resync the relative NEO turn encoder to the absolute encoder.
Private Types
using radians_per_second_squared_t = compound_unit< radians, inverse< squared< second >>>
Private Member Functions
void EncoderToRadians ()
Calculate the m_absAngle based on the pulse widths from m_pulseWidthCallback.
double MinTurnRads (double init, double final, bool &bOutputReverse)
meters_per_second_t CalcMetersPerSec ()
double CalcTicksPer100Ms (meters_per_second_t speed)
Private Attributes
double m_offset
The offset, in pulse widths, for syncing the relative encoder to the absolute encoder.
std::string m_name
String used to identify each pod, used for SmartDashboard prints.
double m_absAngle = 0.0
Absolute angle calculated from the absolute encoder pulse widths.
TalonFX m_driveMotor
Falon 500 that drives the pod.
DrivePidParams2 m_drivePidParams
PID param loader for the TalonFX.
TurnPidParams2 m_turnPidParams
PID param loader for the CANSparkMax.
GetPulseWidthCallback m_pulseWidthCallback
CANifier::PWMChannel m_pwmChannel
Timer m_timer
Timer used to sync absolute and relative encoders on robot turn on.
NEO that turns the pod, controls angle with relative encoder and PID
CANSparkMax m_turningMotor
CANEncoder m_turnRelativeEncoder
CANPIDController m_turnPIDController = m_turningMotor.GetPIDController()
Detailed Description
Definition at line 171 of file SwerveModule2.h.
Member Typedef Documentation
using SwerveModule2::radians_per_second_squared_t = compound_unit<radians, inverse<squared<second>>> private
Definition at line 173 of file SwerveModule2.h.
Constructor & Destructor Documentation
SwerveModule2::SwerveModule2 (int driveMotorChannel, int turningMotorChannel, GetPulseWidthCallback pulseWidthCallback, CANifier::PWMChannel pwmChannel, bool driveEncoderReversed, double offSet, const std::string & name)
Definition at line 17 of file SwerveModule2.cpp.
References EncoderToRadians(), ModuleConstants::kMotorCurrentLimit, Math::kTau, ModuleConstants::kTurnMotorRevsPerWheelRev, TurnPidParams2::Load(), DrivePidParams2::Load(), m_absAngle, m_driveMotor, m_drivePidParams, m_timer, m_turningMotor, m_turnPIDController, m_turnPidParams, and m_turnRelativeEncoder.
     : m_offset(offset)
     , m_name(name)
     , m_driveMotor(driveMotorChannel)
     , m_turningMotor(turningMotorChannel, CANSparkMax::MotorType::kBrushless)
     , m_pulseWidthCallback(pulseWidthCallback)
     , m_pwmChannel(pwmChannel)
 {
     StatorCurrentLimitConfiguration statorLimit { true, ModuleConstants::kMotorCurrentLimit, ModuleConstants::kMotorCurrentLimit, 2 };
     m_driveMotor.ConfigStatorCurrentLimit(statorLimit);
     SupplyCurrentLimitConfiguration supplyLimit { true, ModuleConstants::kMotorCurrentLimit, ModuleConstants::kMotorCurrentLimit, 2 };
     m_driveMotor.ConfigSupplyCurrentLimit(supplyLimit);
     m_turningMotor.SetSmartCurrentLimit(ModuleConstants::kMotorCurrentLimit);
     // Set up GetVelocity() to return meters per sec instead of RPM
     m_turnRelativeEncoder.SetPositionConversionFactor(Math::kTau / ModuleConstants::kTurnMotorRevsPerWheelRev);
     m_driveMotor.SetInverted(driveMotorReversed ? TalonFXInvertType::CounterClockwise : TalonFXInvertType::Clockwise);
     m_turningMotor.SetInverted(false);
     m_driveMotor.ConfigSelectedFeedbackSensor(TalonFXFeedbackDevice::IntegratedSensor);
     m_turnPIDController.SetFeedbackDevice(m_turnRelativeEncoder);
     m_turningMotor.SetIdleMode(CANSparkMax::IdleMode::kBrake);
     m_driveMotor.SetNeutralMode(NeutralMode::Brake);
     EncoderToRadians();
     m_turnRelativeEncoder.SetPosition(m_absAngle); // Tell the encoder where the absolute encoder is
     m_drivePidParams.Load(m_driveMotor);
     m_turnPidParams.Load(m_turnPIDController);
     m_timer.Reset();
     m_timer.Start();
 }
Member Function Documentation
void SwerveModule2::Periodic ()
Definition at line 58 of file SwerveModule2.cpp.
References CalcMetersPerSec(), EncoderToRadians(), m_absAngle, m_name, m_timer, m_turnPIDController, and m_turnRelativeEncoder.
 {
     EncoderToRadians();
     if (m_timer.Get() < 5)
     {
         // printf( "Seeding the relative encoder with absolute encoder: %.3f %.3f %.3f \n",
         //         fabs(m_absAngle - m_turnRelativeEncoder.GetPosition()),
         //         m_absAngle,
         //         m_turnRelativeEncoder.GetPosition());
         m_turnRelativeEncoder.SetPosition(m_absAngle); // Tell the relative encoder where the absolute encoder is
     }
     SmartDashboard::PutNumber("D_SM_Rel " + m_name, m_turnRelativeEncoder.GetPosition());
     // SmartDashboard::PutNumber("D_SM_Abs " + m_name, m_absAngle);
     SmartDashboard::PutNumber("D_SM_AbsDiff " + m_name, m_turnRelativeEncoder.GetPosition() - m_absAngle);
     SmartDashboard::PutNumber("D_SM_MPS " + m_name, CalcMetersPerSec().to<double>());
     SmartDashboard::PutNumber("D_SM_IError " + m_name, m_turnPIDController.GetIAccum());
     // SmartDashboard::PutNumber("D_SM_TP100MS " + m_name, m_driveMotor.GetSelectedSensorVelocity());
     // SmartDashboard::PutNumber("D_SM_RelToAbsError " + m_name, m_absAngle - m_turnRelativeEncoder.GetPosition());
 }
frc::SwerveModuleState SwerveModule2::GetState ()
Get the state for the swerve module pod
Returns
The state (vector with speed and angle) representig the current module state
Todo:
Currently GetState uses the absolute angle instead of the relative angle that we should be using
Definition at line 80 of file SwerveModule2.cpp.
References CalcMetersPerSec(), EncoderToRadians(), and m_absAngle.
 {
     EncoderToRadians();
     return { CalcMetersPerSec(), frc::Rotation2d(radian_t(m_absAngle))};
 }
void SwerveModule2::SetDesiredState (frc::SwerveModuleState & state)
Set the desired state for the swerve module pod
Parameters
state The state (vector with speed and angle) representing the desired module state
Definition at line 86 of file SwerveModule2.cpp.
References CalcTicksPer100Ms(), TurnPidParams2::LoadFromNetworkTable(), m_driveMotor, m_name, m_turnPIDController, m_turnPidParams, m_turnRelativeEncoder, and MinTurnRads().
 {
     // Retrieving turn PID values from SmartDashboard
     // m_drivePidParams.LoadFromNetworkTable(m_driveMotor);
     m_turnPidParams.LoadFromNetworkTable(m_turnPIDController);
     // Find absolute encoder and NEO encoder positions
     //EncoderToRadians();
     double currentPosition = m_turnRelativeEncoder.GetPosition();
     // Calculate new turn position given current Neo position, current absolute encoder position, and desired state position
     bool bOutputReverse = false;
     double minTurnRads = MinTurnRads(currentPosition, state.angle.Radians().to<double>(), bOutputReverse);
     double direction = 1.0; // Sent to TalonFX
     if (bOutputReverse)
         direction = -1.0;
     // Set position reference of turnPIDController
     double newPosition = currentPosition + minTurnRads;
     if (state.speed != 0_mps) {
         #ifdef DISABLE_DRIVE
         m_driveMotor.Set(TalonFXControlMode::Velocity, 0.0);
         #else
         m_driveMotor.Set(TalonFXControlMode::Velocity, direction * CalcTicksPer100Ms(state.speed));
         #endif
     }
     else {
         m_driveMotor.Set(TalonFXControlMode::PercentOutput, 0.0);
     }
     // Set the angle unless module is coming to a full stop
     if (state.speed.to<double>() != 0.0)
         m_turnPIDController.SetReference(newPosition, rev::ControlType::kPosition);
     SmartDashboard::PutNumber("D_SM_SetpointMPS " + m_name, state.speed.to<double>());
     // SmartDashboard::PutNumber("D_SM_Error " + m_name, newPosition - m_turnRelativeEncoder.GetPosition());
 }
void SwerveModule2::ResetEncoders ()
Resets the drive motor encoders to 0.
Definition at line 127 of file SwerveModule2.cpp.
References m_driveMotor.
 {
     m_driveMotor.SetSelectedSensorPosition(0.0);
 }
void SwerveModule2::ResetRelativeToAbsolute ()
Resync the relative NEO turn encoder to the absolute encoder.
Definition at line 142 of file SwerveModule2.cpp.
References m_absAngle, and m_turnRelativeEncoder.
 {
     // printf( "Seeding the relative encoder with absolute encoder: %.3f %.3f %.3f \n",
     //             fabs(m_absAngle - m_turnRelativeEncoder.GetPosition()),
     //             m_absAngle,
     //             m_turnRelativeEncoder.GetPosition());
     m_turnRelativeEncoder.SetPosition(m_absAngle);
 }
void SwerveModule2::EncoderToRadians () private
Calculate the m_absAngle based on the pulse widths from m_pulseWidthCallback.
Definition at line 132 of file SwerveModule2.cpp.
References DriveConstants::kPulseWidthToRadians, Math::kTau, m_absAngle, m_name, m_offset, m_pulseWidthCallback, and m_pwmChannel.
 {
     double pulseWidth = m_pulseWidthCallback(m_pwmChannel);
     // Pulse Width per rotation is not equal for all encoders. Some are 0 - 3865, some are 0 - 4096
     m_absAngle = fmod((pulseWidth - m_offset) * DriveConstants::kPulseWidthToRadians + Math::kTau, Math::kTau);
     SmartDashboard::PutNumber("D_SM_PW " + m_name, pulseWidth);
     SmartDashboard::PutNumber("D_SM_AA " + m_name, m_absAngle);
     // Convert CW to CCW? m_absAngle = Math::kTau - m_absAngle;
 }
double SwerveModule2::MinTurnRads (double init, double final, bool & bOutputReverse) private
Determine the smallest magnitude delta angle that can be added to initial angle that will result in an angle equivalent (but not necessarily equal) to final angle. All angles in radians Currently final - init difference is always chosen regardless of angle
Definition at line 156 of file SwerveModule2.cpp.
References Util::NegPiToPiRads(), and Util::ZeroTo2PiRads().
 {
     init = Util::ZeroTo2PiRads(init);
     final = Util::ZeroTo2PiRads(final);
     // The shortest turn angle may be acheived by reversing the motor output direction
     double angle1 = final - init;
     double angle2 = final + wpi::math::pi - init;
     angle1 = Util::NegPiToPiRads(angle1);
     angle2 = Util::NegPiToPiRads(angle2);
     // Choose the smallest angle and determine reverse flag
     //TODO: FINISHED ROBOT TUNING
     // Eventually prefer angle 1 always during high speed to prevent 180s
     // if (fabs(angle1) <= 2 * fabs(angle2))
     // {
         bOutputReverse = false;
         return angle1;
     // }
     // else
     // {
     //     bOutputReverse = true;
     //     return angle2;
     // }
 }
meters_per_second_t SwerveModule2::CalcMetersPerSec () private
Calculate the MPS of the drive motor based on its current encoder tick velocity
Returns
Meters per second
Definition at line 185 of file SwerveModule2.cpp.
References ModuleConstants::kDriveEncoderMetersPerSec, and m_driveMotor.
 {
    double ticksPer100ms = m_driveMotor.GetSelectedSensorVelocity();
    return meters_per_second_t(ModuleConstants::kDriveEncoderMetersPerSec * ticksPer100ms);
 }
double SwerveModule2::CalcTicksPer100Ms (meters_per_second_t speed) private
Calculate drive motor encoder ticks based on the MPS
Parameters
speed Meters per second
Returns
Encoder ticks
Definition at line 191 of file SwerveModule2.cpp.
References ModuleConstants::kDriveEncoderMetersPerSec.
 {
    return speed.to<double>() / ModuleConstants::kDriveEncoderMetersPerSec;
 }
Member Data Documentation
double SwerveModule2::m_offset private
The offset, in pulse widths, for syncing the relative encoder to the absolute encoder.
Definition at line 216 of file SwerveModule2.h.
std::string SwerveModule2::m_name private
String used to identify each pod, used for SmartDashboard prints.
Definition at line 218 of file SwerveModule2.h.
double SwerveModule2::m_absAngle = 0.0 private
Absolute angle calculated from the absolute encoder pulse widths.
Definition at line 220 of file SwerveModule2.h.
TalonFX SwerveModule2::m_driveMotor private
Falon 500 that drives the pod.
Definition at line 223 of file SwerveModule2.h.
CANSparkMax SwerveModule2::m_turningMotor private
Definition at line 226 of file SwerveModule2.h.
CANEncoder SwerveModule2::m_turnRelativeEncoder private
Initial value:
= m_turningMotor.GetAlternateEncoder(CANEncoder::AlternateEncoderType::kQuadrature,
                                                                          ModuleConstants::kTurnEncoderCPR)
Definition at line 227 of file SwerveModule2.h.
CANPIDController SwerveModule2::m_turnPIDController = m_turningMotor.GetPIDController() private
Definition at line 229 of file SwerveModule2.h.
DrivePidParams2 SwerveModule2::m_drivePidParams private
PID param loader for the TalonFX.
Definition at line 233 of file SwerveModule2.h.
TurnPidParams2 SwerveModule2::m_turnPidParams private
PID param loader for the CANSparkMax.
Definition at line 235 of file SwerveModule2.h.
GetPulseWidthCallback SwerveModule2::m_pulseWidthCallback private
Callback used to determine the pulse width
Parameters
pwmChannel Channel to decide which absolute encoder's pulse width values are retrieved
Definition at line 239 of file SwerveModule2.h.
CANifier::PWMChannel SwerveModule2::m_pwmChannel private
Definition at line 240 of file SwerveModule2.h.
Timer SwerveModule2::m_timer private
Timer used to sync absolute and relative encoders on robot turn on.
Definition at line 243 of file SwerveModule2.h.
The documentation for this class was generated from the following files:
src/main/include/subsystems/SwerveModule2.h
src/main/cpp/subsystems/SwerveModule2.cpp