FRC Paradigm Shift #1259: CyclerAgitation Class Reference
CyclerAgitation Class Reference
Public Member Functions
CyclerAgitation (CyclerSubsystem *subsystem, double speed)
void Initialize () override
void Execute () override
void End (bool interrupted) override
Private Attributes
CyclerSubsystem * m_cycler
Timer m_timer
double m_speed
Detailed Description
Definition at line 12 of file CyclerAgitation.h.
Constructor & Destructor Documentation
CyclerAgitation::CyclerAgitation (CyclerSubsystem * subsystem, double speed) explicit
Definition at line 9 of file CyclerAgitation.cpp.
  : m_cycler(subsystem)
  , m_timer()
  , m_speed(speed)
  {
   AddRequirements({subsystem});
 }
Member Function Documentation
void CyclerAgitation::Initialize () override
Definition at line 17 of file CyclerAgitation.cpp.
References m_cycler, m_timer, and CyclerSubsystem::ResetSensor().
 {
     // Ensures that cycler position is not valid
     m_cycler->ResetSensor();
     m_timer.Start();
 }
void CyclerAgitation::Execute () override
Definition at line 24 of file CyclerAgitation.cpp.
References CyclerConstants::kTimePassed, m_cycler, m_speed, m_timer, and CyclerSubsystem::SetTurnTable().
 {
     if (m_timer.Get() <= kTimePassed * 1) {
         m_cycler->SetTurnTable(m_speed);
     }
     else if (m_timer.Get() <= kTimePassed * 2) {
         m_cycler->SetTurnTable(0);
     }
     else if (m_timer.Get() <= kTimePassed * 3) {
         m_cycler->SetTurnTable(m_speed * -1.0);
     }
     else if (m_timer.Get() <= kTimePassed * 4) {
         m_cycler->SetTurnTable(0);
     }
     else if (m_timer.Get() > kTimePassed * 4) {
         m_timer.Reset();
     }
 }
void CyclerAgitation::End (bool interrupted) override
Definition at line 43 of file CyclerAgitation.cpp.
References m_cycler, and CyclerSubsystem::SetTurnTable().
 {
     m_cycler->SetTurnTable(0);
 }
Member Data Documentation
CyclerSubsystem* CyclerAgitation::m_cycler private
Definition at line 23 of file CyclerAgitation.h.
Timer CyclerAgitation::m_timer private
Definition at line 24 of file CyclerAgitation.h.
double CyclerAgitation::m_speed private
Definition at line 25 of file CyclerAgitation.h.
The documentation for this class was generated from the following files:
src/main/include/commands/CyclerAgitation.h
src/main/cpp/commands/CyclerAgitation.cpp