FRC Paradigm Shift #1259: CyclerPrepare Class Reference
CyclerPrepare Class Reference
Public Member Functions
CyclerPrepare (CyclerSubsystem *subsystem, bool reset)
void Initialize () override
void Execute () override
bool IsFinished () override
void End (bool interrupted) override
Private Attributes
CyclerSubsystem * m_cycler
bool reset
Detailed Description
Definition at line 10 of file CyclerPrepare.h.
Constructor & Destructor Documentation
CyclerPrepare::CyclerPrepare (CyclerSubsystem * subsystem, bool reset) explicit
Definition at line 6 of file CyclerPrepare.cpp.
References m_cycler, and CyclerSubsystem::ResetSensor().
  : m_cycler(subsystem)
 {
     AddRequirements({subsystem});
     if (reset)
         m_cycler->ResetSensor();
 }
Member Function Documentation
void CyclerPrepare::Initialize () override
Definition at line 14 of file CyclerPrepare.cpp.
References m_cycler, and CyclerSubsystem::StartDetection().
{
     m_cycler->StartDetection();
 }
void CyclerPrepare::Execute () override
Definition at line 18 of file CyclerPrepare.cpp.
References CyclerConstants::kTurnTableHoneSpeed, m_cycler, CyclerSubsystem::SetFeeder(), and CyclerSubsystem::SetTurnTable().
{
     m_cycler->SetTurnTable(kTurnTableHoneSpeed);
     m_cycler->SetFeeder(0);
 }
bool CyclerPrepare::IsFinished () override
Definition at line 24 of file CyclerPrepare.cpp.
{
     return true; //m_cycler->AtPosition();
 }
void CyclerPrepare::End (bool interrupted) override
Definition at line 28 of file CyclerPrepare.cpp.
References m_cycler, CyclerSubsystem::ResetSensor(), CyclerSubsystem::SetFeeder(), and CyclerSubsystem::SetTurnTable().
{
     if (interrupted) {
         m_cycler->ResetSensor();
     }
     m_cycler->SetFeeder(0);
     m_cycler->SetTurnTable(0);
 }
Member Data Documentation
CyclerSubsystem* CyclerPrepare::m_cycler private
Definition at line 20 of file CyclerPrepare.h.
bool CyclerPrepare::reset private
Definition at line 21 of file CyclerPrepare.h.
The documentation for this class was generated from the following files:
src/main/include/commands/CyclerPrepare.h
src/main/cpp/commands/CyclerPrepare.cpp